backend/models/Region.php
<?php 
namespace backend\models;


class Region extends \common\models\Entity
{
    /**
     * Return region list for dropdown list
     * @return array
     */
    public static function getRegions()
    {
        $query = self::find()
                ->select('id, name')
                ->where(['type' => self::TYPE_REGION])
                ->orderBy('name')
                ->asArray();

        return $query->all();
    }
}

backend/controllers/RegionController.php
<?php

namespace backend\controllers;

use common\components\helpers\WordHelper;
use backend\models\EntitySearch;
use backend\models\Entity;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * 
 */
class RegionController extends Controller
{
    /**
     * Region list
     */
    public function actionIndex($type, $region = 0)
    {
        $searchModel = new EntitySearch(['type' => $type]);

        if ($region > 0) {
            $region = Entity::find()->where(['id' => $region, 'type' => Entity::TYPE_REGION])->one();
            if (!$region) {
                throw new NotFoundHttpException;
            }
            $searchModel->parent_id = $region->id;
        } else {
            $searchModel->parent_id = $region;
        }

        $dataProvider = $searchModel->search();

        return $this->render(
            'list', 
            [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'region' => $region,
                'type' => $type,
            ]
        );
    }

    public function actionCreate($type, $region = 0)
    {
        if ($region > 0) {
            $region = Entity::find()->where(['id' => $region, 'type' => Entity::TYPE_REGION])->one();
            if (!$region) {
                throw new NotFoundHttpException;
            }
        }

        $model = new Entity(['type' => $type]);

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $model->parent_id = $model->type == Entity::TYPE_CITY ? $region->id : 0;
            if ($model->save()) {
                $redirect = $model->type == Entity::TYPE_CITY ? ['region/index', 'region' => $region->id, 'type' => 'cities'] : ['region/index', 'type' => 'regions'];
                $this->redirect($redirect);  
            }
        }

        return $this->render('form', [
            'model' => $model,
            'region' => $region
        ]);
    }

    public function actionUpdate($id, $type)
    {
        $model = Entity::find()->where(['type' => $type, 'id' => $id])->with('parent')->one();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                $redirect = $model->type == Entity::TYPE_CITY ? ['region/index', 'region' => $model->parent->id, 'type' => 'cities'] : ['region/index', 'type' => 'regions'];
                $this->redirect($redirect);  
            }
        }

        return $this->render('form', [
            'model' => $model,
            'region' => $model->parent,
        ]);
    }

    /**
     * Get cities of region
     * @return string
     */
    public function actionCities()
    {
        $regionID = \Yii::$app->request->post('region');

        if ($regionID) {

            $region = Entity::find($regionID)->where([
                'type' => Entity::TYPE_REGION,
                'id'   => $regionID,
            ])->one();

            if ($region) {
                $cities = Entity::find()->select('id, name')->where([
                    'type' => Entity::TYPE_CITY,
                    'parent_id' => $region->id
                ])->orderBy('name')->asArray()->all();

                return json_encode($cities);
            }
        }

        return null;
    }
}

backend/views/region/form.php
<?php

use backend\models\Entity;
use common\components\helpers\WordHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = ($model->type == Entity::TYPE_CITY ? $region->name.': ' : '').($model->isNewRecord ? \Yii::t('main','New '.$model->type) : $model->name );

?>
<p>&nbsp;</p>
<?php $form = ActiveForm::begin([
    'id' => 'entity-form', 
    'layout' => 'horizontal',
    'enableClientScript' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-2',
            'offset' => 'col-sm-offset-4',
            'wrapper' => 'col-sm-6',
        ],
    ],
]); ?>
<?= $form->field($model, 'name') ?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
        <?= Html::a('Отменить', ($model->type == Entity::TYPE_CITY ? ['region/index', 'type' => WordHelper::pluralize($model->type), 'region' => $region->id] : ['region/index', 'type' => WordHelper::pluralize($model->type)]), ['class' => 'btn btn-default', 'name' => 'cancel-button']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/region/list.php
<?php

use backend\models\Entity;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;


$this->title = $type == 'cities' ? $region->name : \Yii::t('main', $type);

$this->params['top_buttons'][] = [
    'label' => 'Добавить',
    'url' => ($type == 'cities' ? ['region/create', 'type' => $searchModel->type, 'region' => $region->id] : ['region/create', 'type' => $searchModel->type]),
    'options' => ['class' => 'btn btn-success btn-sm pull-right']
];

if ($type == 'cities') {
    $this->params['top_buttons'][] = [
            'label' => 'Все регионы',
            'url' => ['region/index', 'type' => 'regions'],
            'options' => ['class' => 'btn btn-default btn-sm pull-right', 'style' => 'margin-right: 5px;']
    ];
}

echo GridView::widget(
    [
        'id' => 'entity-grid',
        'summary' => '',
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'name',
                'label' => \Yii::t('main', 'Name'),
                'format' => 'html',
                'value' => function($model) {
                    return ($model['type'] == Entity::TYPE_REGION) ? Html::a($model['name'], ['region/index', 'region' => $model['id'], 'type' => 'cities']) : $model['name'];
                }
            ],
            [
                'attribute' => 'childs',
                'label' => \Yii::t('main', 'Cities num'),
                'visible' => ($type == 'regions') ? true : false,
            ],
            [
                'attribute' => 'created_at',
                'label' => \Yii::t('main', 'created_at'),
                'format' => ['date', 'php:Y-m-d H:i:s']
            ],
            [
                'attribute' => 'updated_at',
                'label' => \Yii::t('main', 'updated_at'),
                'format' => ['date', 'php:Y-m-d H:i:s']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['region/update', 'id' => $model['id'], 'type' => $model['type']]);
                    },
                    'delete' => function($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', '#');
                    }
                ],
            ],

        ]
    ]
);
?>