backend/models/School.php
<?php 

namespace backend\models;

use yii\helpers\ArrayHelper;

/**
 * 
 */
class School extends \common\models\School
{
    /**
     * Return formated school name
     * @return string
     */
    public function getTitle()
    {
        $title = [];

        if ($this->number != ''){
            $title[] = '№ '.$this->number;
        }

        if ($this->name != '') {
            $title[] = $this->name;
        }

        return \Yii::t('main', $this->type).(!empty($title) ? ': '.implode($title, ', ') : '');
    }

    /**
     * Returns number of schools by type
     * @return array
     */
    public static function countSchoolsByType()
    {
        $query = (new \yii\db\Query())
            ->select('type, COUNT(*) as num')
            ->from(self::tableName())
            ->where(['type' => array_keys(self::getSchoolTypes())])
            ->groupBy('type')->all();

        $data['total'] = 0;
        foreach ($query as $row) {
            $data[$row['type']] = $row['num'];
            $data['total'] = $data['total'] + $data[$row['type']];
        }

        return $data;
    }
}

common/models/School.php
<?php 

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * SchoolBase
 * 
 */
class School extends SchoolBase
{
    /**
     * Base region of region_id
     * @var integer
     */
    public $region_id;

    /**
     * @inhertidoc
     */
    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(), [
                [['region_id'], 'integer'],
                [['region_id'], 'compare', 'compareValue' => 1, 'operator' => '>=', 'message' => 'Необходимо выбрать регион'],
                [['city_id'], 'required', 'message' => 'Необходимо выбрать город или район'],
                [['type'], 'validateSchoolType'],
                [['city_id'], 'validateCity'],
            ]
        );
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'region_id' => 'Регион',
            'city_id' => 'Город или район',
            'type' => Yii::t('main', 'School Type'),
        ]);
    }

    /**
     * Validates selected city
     * @return void
     */
    public function validateCity()
    {
        if (isset($this->region_id) && isset($this->city_id)) {
            $cityExists = Entity::find()->where([
                'id' => $this->city_id, 
                'parent_id' => $this->region_id,
                'type' => Entity::TYPE_CITY
            ])->exists();

            if (!$cityExists) {
                $this->addError('city_id', 'Неправильный город или район');
            }
        }
    }

    /**
     * Declaring Relations
     * 
     */
    public function getCity()
    {
        return $this->hasOne(Entity::className(), ['id' => 'city_id']);
    }

    /**
     * Returns school type
     * @return array
     */
    public static function getSchoolTypes()
    {
        return [
            self::TYPE_SCHOOL => Yii::t('main', self::TYPE_SCHOOL),
            self::TYPE_LYCEUM => Yii::t('main', self::TYPE_LYCEUM),
            self::TYPE_COLLEGE => Yii::t('main', self::TYPE_COLLEGE),
            self::TYPE_UNIVERSITY => Yii::t('main', self::TYPE_UNIVERSITY)
        ];
    }

    /**
     * Validates school type
     * @return void
     */
    public function validateSchoolType()
    {
        if (isset($this->type) && !empty($this->type)) {
            if (!array_key_exists($this->type, $this->getSchoolTypes())){
                $this->addError('type', Yii::t('main', 'Wrong school type'));
            }
        }
    } 

    /**
     * Declaring Relations with SchoolStaff ar
     * 
     */
    public function getStaff()
    {
        return $this->hasMany(SchoolStaff::className(), ['school_id' => 'id']);    
    }

    /**
     * Declaring Relations with BankDetail ar
     * 
     */
    public function getBankDetails()
    {
        return $this->hasMany(BankDetail::className(), ['school_id' => 'id']);    
    }

    /**
     * Returns number of assigned users
     * @return integer
     */
    protected function countAssignedUsers($type = [])
    {
        return (new \yii\db\Query)
                ->from(['staff' => SchoolStaff::tableName()])
                ->leftJoin(['user' => User::tableName()], 'staff.user_id = user.id')
                ->where(['staff.school_id' => $this->id, 'user.status' => User::STATUS_ACTIVE, 'staff.type' => !empty($type) ? $type : SchoolStaff::types()])
                ->count();    
    }

    /**
     * Counts assigned staff
     * @return integer
     */
    public function countStaff()
    {
        return $this->countAssignedUsers(SchoolStaff::TYPE_STAFF);
    }

    /**
     * Counts assigned students
     * @return integer
     */
    public function countStudents()
    {
        return $this->countAssignedUsers(SchoolStaff::TYPE_STUDENT);
    }

    /**
     * Counts assigned student parents
     * @return integer
     */
    public function countParents()
    {
        return $this->countAssignedUsers(SchoolStaff::TYPE_PARENT);
    }
}

backend/controllers/SchoolController.php
<?php

namespace backend\controllers;

use backend\models\Region;
use backend\models\School;
use backend\models\SchoolSearch;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * 
 */
class SchoolController extends Controller
{
    /**
     * School list
     * @param  string $type School type
     */
    public function actionIndex($type)
    {
        $searchModel = new SchoolSearch(['type' => $type]);
        $dataProvider = $searchModel->search();

        return $this->render(
            'list', 
            [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'type' => $type,
            ]
        );
    }

    /**
     * Creates school, college, lyceum, university
     * @param  string $type School type
     */
    public function actionCreate($type)
    {
        $model = new School(['type' => $type]);
        
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->status = School::STATUS_ACTIVE;
            if ($model->makeRoot()) {
                $this->redirect(['/'.$model->type.'/'.$model->id]);  
            }
        }

        return $this->render(
            'form', 
            [
                'regions' => ArrayHelper::map(Region::getRegions(), 'id', 'name'),
                'model' => $model
            ]
        );
    }

    /**
     * Update school infor
     * @param  string $type School type
     * @param  integer $id School id
     */
    public function actionUpdate($type, $id)
    {
        $model = School::find()->where([
            'id' => $id, 
            'type' => $type,
            'status' => School::STATUS_ACTIVE,
        ])->with('city')->one();

        if (!$model) {
            throw new NotFoundHttpException;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save(false)) {
                $this->redirect(['/'.$model->type.'/'.$model->id]);  
            }
        }

        $model->region_id = $model->city->parent_id;

        return $this->render(
            'form', 
            [
                'regions' => ArrayHelper::map(Region::getRegions(), 'id', 'name'),
                'model' => $model
            ]
        );
    }

    /**
     * View schol basic info
     * @param  string $type School type: school, college, lyceum, university...
     * @param  integer $id School id
     */
    public function actionView($type, $id)
    {
        $model = School::find()->where([
            'id' => $id, 
            'type' => $type,
            'status' => School::STATUS_ACTIVE,
        ])->with('city.parent')->one();

        if (!$model) {
            throw new NotFoundHttpException;
        }

        return $this->render(
            'view',
            [
                'type' => $type,
                'model' => $model,
            ]
        );
    }

}

backend/views/school/form.php
<?php

use common\components\helpers\WordHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = $model->getTitle();

$this->render('//school/menu', ['school' => $model, 'current' => 'basic']);

?>
<p>&nbsp;</p>
<?php $form = ActiveForm::begin([
    'id' => 'school-form', 
    'layout' => 'horizontal',
    'enableClientScript' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-3',
            'offset' => 'col-sm-offset-2',
            'wrapper' => 'col-sm-6',
        ],
    ],
]); ?>
<?= $form->field($model, 'number') ?>
<?= $form->field($model, 'name') ?>
<?= $form->field($model, 'phone') ?>
<?= $form->field($model, 'fax') ?>
<?= $form->field($model, 'email') ?>
<?= $form->field($model, 'website') ?>
<?= $form->field($model, 'inn') ?>
<?= $form->field($model, 'okonx') ?>
<?= $form->field($model, 'region_id')->dropDownList(ArrayHelper::merge(['0' => 'Выберите регион'], $regions), ['id' => 'regions']) ?>
<?= $form->field($model, 'city_id')->dropDownList([], ['id' => 'city','disabled' => 'true']) ?>
<?= Html::input('hidden','selectedCity', isset($model->city->id) ? $model->city->id : 0, ['id'=>'selectedCity']) ?>
<?php if (!$model->isNewRecord) { ?>
<?= $form->field($model, 'type')->dropDownList($model->getSchoolTypes()) ?>
<?php } ?>
<?= $form->field($model, 'address')->textarea() ?>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-6">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
        <?= Html::a('Отменить', ($model->isNewRecord ? ['school/index', 'type' => WordHelper::pluralize($model->type)] : ['school/view', 'id' => $model->id, 'type' => $model->type]), ['class' => 'btn btn-default', 'name' => 'cancel-button']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/school/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;


$this->title = \Yii::t('main', $type);

$this->params['top_buttons'] = [
    [
        'label' => 'Добавить',
        'url' => ['/school/create', 'type' => $searchModel->type],
        'options' => ['class' => 'btn btn-success btn-sm pull-right']
    ]
];

Pjax::begin();
echo GridView::widget(
    [
        'id' => 'schools-grid',
        'summary' => '',
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'name',
                'format' => 'raw',
                'label' => 'Название',
                'value' => function ($model) {
                    return Html::a($model['name'], ['/school/view', 'id' => $model['id'], 'type' => $model['type']], ['data-pjax' => 0]);
                }
            ],
            [
                'attribute' => 'number',
                'format' => 'raw',
                'label' => 'Номер',
                'value' => function ($model) {
                    return Html::a($model['number'], ['/school/view', 'id' => $model['id'], 'type' => $model['type']], ['data-pjax' => 0]);
                }
            ],
            [
                'attribute' => 'phone',
                'label' => 'Телефон'
            ],
            [
                'attribute' => 'fax',
                'label' => 'Факс'
            ],
            [
                'attribute' => 'email',
                'label' => 'Email адрес'
            ],
            [
                'attribute' => 'region',
                'format' => 'raw',
                'label' => 'Регион',
                'value' => function ($model) {
                    return $model['region'].', '.$model['city'];
                }
            ],
        ]
    ]
);
Pjax::end();
?>

backend/views/school/menu.php
<?php

use backend\components\widgets\TabMenuWidget;
use common\components\helpers\WordHelper;

$this->title = $school->getTitle();

$this->params['top_buttons'] = [
    [
        'label' => \Yii::t('main', WordHelper::pluralize($school->type).'_list'),
        'url' => ['/school/index', 'type' => WordHelper::pluralize($school->type)],
        'options' => ['class' => 'btn btn-default btn-sm pull-right']
    ]
];

$this->params['tabs'] = [
    [
        'label'  => 'Общая информация',
        'link'   => ['school/view', 'id' => $school->id, 'type' => WordHelper::singularize($school->type)],
        'active' => $current == 'basic' ? true : false,
    ],
    [
        'label' => 'Сотрудники ('.$school->countStaff().')',
        'link'  => (!$school->isNewRecord ? ['staff/index', 'school_type' => $school->type, 'school_id' => $school->id] : '#'),
        'active' => $current == 'staff' ? true : false,
    ],
    [
        'label' => 'Банковские реквизиты ('.$school->getBankDetails()->count().')',
        'link'  => (!$school->isNewRecord ? ['bank/index', 'school_type' => $school->type, 'school_id' => $school->id] : '#'),
        'active' => $current == 'bank' ? true : false,
    ],
    [
        'label' => 'Классы',
        'active' => $current == 'class' ? true : false,
    ],
];

?>

backend/views/school/view.php
<?php 

use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = $model->getTitle();
$this->render('//school/menu', ['school' => $model, 'current' => 'basic']);
?>
<p>&nbsp;</p>
<div class="table detail-view-table">
    <?php
        echo DetailView::widget([
            'model' => $model,
            'options' => [
                'class' => 'table table-striped table-bordered',
            ],
            'attributes' => [
                'name',
                'number',
                'phone',
                'fax',
                'email',
                'inn',
                'okonx',
                'website',
                'address',
                [
                    'label' => \Yii::t('main', 'Region'),
                    'value' => $model->city->parent->name.', '.$model->city->name
                ],
            ],
        ]);
    ?> 
    <?= Html::a('Изменить', ['/school/update', 'id' => $model->id, 'type' => $type], ['class' => 'btn btn-primary', 'name' => 'cancel-button']) ?>   
</div>