backend/controllers/BankController.php
<?php

namespace backend\controllers;

use backend\models\BankDetailSearch;
use common\models\BankDetail;
use yii\web\NotFoundHttpException;

/**
 * 
 */
class BankController extends SchoolBaseController
{
    /**
     * Bank list
     * @param  string $type School type
     * @param  string $id   School id
     */
    public function actionIndex($school_type, $school_id)
    {
        $searchBank1 = new BankDetailSearch(['school_id' => $school_id]);
        $searchBank2 = new BankDetailSearch(['school_id' => $school_id, 'is_treasury' => 1]);

        return $this->render('list', [
            'school' => $this->school,
            'schoolBankProvider' => $searchBank1->search(),
            'treasuryBankProvider' => $searchBank2->search(),
        ]);
    }


    public function actionCreate($school_type, $school_id, $treasury = 0)
    {
        $model = new BankDetail(['school_id' => $school_id]);

        if ($treasury == 1) {
            $model->is_treasury = 1;
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                $this->redirect(['bank/index', 'school_id' => $school_id, 'school_type' => $school_type]);  
            }
        }

        return $this->render('form', [
            'school' => $this->school,
            'model' => $model
        ]);
    }

    public function actionUpdate($school_type, $school_id, $id)
    {
        $model = BankDetail::find()->where(['id' => $id, 'school_id' => $school_id])->one();

        if (!$model) {
            throw new \NotFoundHttpException;
        }

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                $this->redirect(['bank/index', 'school_id' => $school_id, 'school_type' => $school_type]);  
            }
        }
        return $this->render('form', [
            'school' => $this->school,
            'model' => $model
        ]);
    }
}

backend/views/bank/form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->render('//school/menu', ['school' => $school, 'current' => 'bank']);

?>
<p>&nbsp;</p>
<?php $form = ActiveForm::begin([
    'id' => 'school-form', 
    'layout' => 'horizontal',
    'enableClientScript' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-2',
            'offset' => 'col-sm-offset-4',
            'wrapper' => 'col-sm-6',
        ],
    ],
]); ?>
<?php if ($model->is_treasury == 1) { ?>
<?= $form->field($model, 'treasury_name') ?>
<?php  } ?>
<?= $form->field($model, 'number') ?>
<?= $form->field($model, 'name') ?>
<?= $form->field($model, 'mfo') ?>
<?php if ($model->is_treasury == 1) { ?>
<?= $form->field($model, 'inn') ?>
<?php  } ?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
        <?= Html::a('Отменить', ['bank/index', 'school_type' => $school->type, 'school_id' => $school->id], ['class' => 'btn btn-default', 'name' => 'cancel-button']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/bank/list.php
<?php 

/* School bank details */

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->render('//school/menu', ['school' => $school, 'current' => 'bank']);
?>
<p>&nbsp;</p>
<h4>
    Банковские реквизиты
    <?= Html::a('Добавить', ['bank/create', 'school_id' => $school->id, 'school_type' => $school->type], ['class' => 'btn btn-success btn-xs pull-right'])?>
</h4>
<?php
Pjax::begin();
echo GridView::widget(
    [
        'id' => 'bank-account-grid',
        'summary' => '',
        'sorter' => [],
        'dataProvider' => $schoolBankProvider,
        'columns' => [
            'name',
            'number',
            'mfo',
            [
                'attribute' => 'inn',
                'label' => \Yii::t('main','INN'),
                'value' => function($model) use ($school) {
                    return $school->inn;
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['bank/update', 'school_type' => $school->type, 'school_id' => $school->id, 'id' => $model->id]);
                    },
                    'delete' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', '#');
                    }
                ],
            ],
        ]
    ]
);
Pjax::end();
?>
<p>&nbsp;</p>
<h4>
    Банковские реквизиты казначейство
     <?= Html::a('Добавить', ['bank/create', 'school_id' => $school->id, 'school_type' => $school->type, 'treasury' => 1], ['class' => 'btn btn-success btn-xs pull-right'])?>
</h4>
<?php
Pjax::begin();
echo GridView::widget(
    [
        'id' => 'bank-account-grid',
        'summary' => '',
        'dataProvider' => $treasuryBankProvider,
        'columns' => [
            'treasury_name',
            'name',
            'number',
            'mfo',
            'inn',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['bank/update', 'school_type' => $school->type, 'school_id' => $school->id, 'id' => $model->id]);
                    },
                    'delete' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', '#');
                    }
                ],
            ],
        ]
    ]
);
Pjax::end();
?>