backend/controllers/StaffController.php
<?php

namespace backend\controllers;

use backend\models\SchoolStaffSearch;
use backend\models\SchoolStaffProfile;
use yii\web\NotFoundHttpException;


/**
 * 
 */
class StaffController extends SchoolBaseController
{
    /**
     * Staff list
     * @param  string $type School type
     * @param  string $id   School id
     */
    public function actionIndex($school_type, $school_id)
    {
        $searchStaff = new SchoolStaffSearch(['school_id' => $school_id]);

        return $this->render('list', [
            'school' => $this->school,
            'schoolStaffProvider' => $searchStaff->search(),
        ]);
    }

    public function actionCreate($school_type, $school_id)
    {
        $model = new SchoolStaffProfile(['school_id' => $school_id]);
        
        if ($model->load(\Yii::$app->request->post()) && $model->create()) {  
            $this->redirect(['staff/index', 'school_id' => $school_id, 'school_type' => $school_type]);  
        }

        return $this->render('form', [
            'school' => $this->school,
            'model' => $model,
            'notAllowedRoles' => $model->getNotAllowedRoles(),
        ]);
    }

    public function actionUpdate($school_type, $school_id, $id)
    {
        $model = (new SchoolStaffSearch(['school_id' => $school_id]))->searchOne(['id' => $id]);

        if (!$model) {
            throw new NotFoundHttpException();
        }

        if ($model->load(\Yii::$app->request->post()) && $model->updateProfile()) { 
            $this->redirect(['staff/index', 'school_id' => $school_id, 'school_type' => $school_type]);
        }

        return $this->render('form', [
            'school' => $this->school,
            'model' => $model,
            'notAllowedRoles' => $model->getNotAllowedRoles(),
        ]);
    }

    public function actionDelete($school_type, $school_id, $id)
    {
        $model = (new SchoolStaffSearch(['school_id' => $school_id]))->searchOne(['id' => $id]);

        if (!$model) {
            throw new NotFoundHttpException();
        }

        if ($model->deleteProfile()) { 
            $this->redirect(['staff/index', 'school_id' => $school_id, 'school_type' => $school_type]);
        }
    }
}

backend/views/staff/form.php
<?php 

/* School staff form */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->render('//school/menu', ['school' => $school, 'current' => 'staff']);

?>
<p>&nbsp;</p>
<?php $form = ActiveForm::begin([
    'id' => 'school-form', 
    'layout' => 'horizontal',
    'enableClientScript' => false,
    'fieldConfig' => [
        'horizontalCssClasses' => [
            'label' => 'col-sm-2',
            'offset' => 'col-sm-offset-4',
            'wrapper' => 'col-sm-6',
        ],
    ],
]); ?>
<?= $form->field($model, 'lastname') ?>
<?= $form->field($model, 'firstname') ?>
<?= $form->field($model, 'middlename') ?>
<?= $form->field($model, 'mobile', ['inputTemplate' => "<div class=\"input-group\"><div class=\"input-group-addon\">+998</div>{input}</div>"]) ?>
<?= $form->field($model, 'email') ?>
<?= $form->field($model, 'roles')->checkboxList($model->getSchoolRoles(), ['item' => function($index, $label, $name, $checked, $value) use ($notAllowedRoles, $model) {
        $options = ['label' => $label, 'value' => $value];
        $checked = false;
        if (is_array($notAllowedRoles) && in_array($value, $notAllowedRoles)) {
            $options['disabled'] = true;
        }

        if (is_array($model->roles) && in_array($value, $model->roles)) {
            $checked = true;
        }
        $checkbox  = Html::beginTag('div', ['class' => 'checkbox']);
        $checkbox .= Html::beginTag('label');
        $checkbox .= Html::checkbox($name, $checked, $options);
        $checkbox .= Html::endTag('label');
        $checkbox .= Html::endTag('div');
    return $checkbox;
}]) ?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
        <?= Html::a('Отменить', ['staff/index', 'school_type' => $school->type, 'school_id' => $school->id], ['class' => 'btn btn-default', 'name' => 'cancel-button']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/staff/list.php
<?php 

/* School staff */

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->render('//school/menu', ['school' => $school, 'current' => 'staff']);
?>
<p>&nbsp;</p>
<h4>
    Все сотрудники
    <?= Html::a('Добавить', ['staff/create', 'school_id' => $school->id, 'school_type' => $school->type], ['class' => 'btn btn-success btn-xs pull-right'])?>
</h4>
<?php
Pjax::begin();
echo GridView::widget(
    [
        'id' => 'bank-account-grid',
        'summary' => '',
        'sorter' => [],
        'dataProvider' => $schoolStaffProvider,
        'columns' => [
            [
                'label' => \Yii::t('main','FIO'),
                'value' => function($model){
                    return $model['lastname'].' '.$model['firstname'].' '.$model['middlename'];
                }
            ],
            [
                'label' => \Yii::t('main','Roles'),
                'value' => function($model){
                    $roles = explode(",", $model['roles']);
                    $str = [];
                    foreach ($roles as $role) {
                        $str[] = \Yii::t('main', $role); 
                    }
                    return implode(", ", $str);
                }
            ],
            [
                'attribute' => 'mobile',
                'label' => \Yii::t('main', 'Mobile'),
                'value' => function($model){
                    return '+998 '.$model['mobile'];
                }
            ],
            [
                'attribute' => 'created_at',
                'label' => \Yii::t('main', 'created_at'),
                'format' => ['date', 'php:Y-m-d H:m:s']
            ],
            [
                'attribute' => 'updated_at',
                'label' => \Yii::t('main', 'updated_at'),
                'format' => ['date', 'php:Y-m-d H:m:s']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => ' {reset} {update} {delete}',
                'buttons' => [
                    'update' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['staff/update', 'school_type' => $school->type, 'school_id' => $school->id, 'id' => $model['user_id']]);
                    },
                    'delete' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['staff/delete', 'school_type' => $school->type, 'school_id' => $school->id, 'id' => $model['user_id']], ['data' => ['confirm'=>Yii::t('main', 'Are you sure to delete this user?')]]);
                    },
                    'reset' => function($url, $model) use ($school) {
                        return Html::a('<span class="glyphicon glyphicon-lock"></span>', '#');
                    }
                ],
            ],
        ]
    ]
);
Pjax::end();
?>